id = "lumin-theme"
name = "Lumin"
version = "0.0.2"
schema_version = 1

authors = ["Daksh Sharma <dakshsharma.tech>"]


description = "Peppermint flavored theme; offspring of Vesper & Cursor."
repository = "https://github.com/frypan05/Lumin"