id = "kk-theme"
name = "KK"
version = "0.0.2"
schema_version = 1

authors = ["KK <kk@thetrivium.mozmail.com>"]


description = "Peppermint flavored theme; offspring of Vesper & Cursor. Based on Lumin from Daksh Sharma <dakshsharma.tech>"
repository = "https://github.com/theintjengineer/opaque-lumin"
